---
# -- -- -- -- -- -- -- -- #
# --   MAIN PLAYBOOK   -- #
- name: "onesetup"
  # -- CONNECTION -- #
  hosts: localhost
  connection: local
  # -- VARIABLES -- #
  vars:
    H_USER: "{{ lookup('ansible.builtin.env', 'USER') }}"
    H_HOME: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    H_XDG_CONFIG_HOME: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG_HOME') | default(lookup('ansible.builtin.env', 'HOME') + '/.config/') }}"
    H_ZDOTDIR: "{{ lookup('ansible.builtin.env', 'ZDOTDIR') | default(lookup('ansible.builtin.env', 'HOME') + '/.config/zsh') }}"
