---
# -- CLEANUP -- #
# cleanup yabai directory
- name: "cleanup - yabai directory"
  file:
    path: "{{ H_XDG_CONFIG_HOME }}/yabai"
    state: absent
    force: true
# cleanup borders directory
- name: "cleanup - borders directory"
  file:
    path: "{{ H_XDG_CONFIG_HOME }}/borders"
    state: absent
    force: true

# -- SYMLINK -- #
# symlink yabai directory
- name: "symlink - yabai directory"
  file:
    src: "{{ role_path }}/files/yabai"
    dest: "{{ H_XDG_CONFIG_HOME }}/yabai"
    state: link
    force: true
# symlink borders directory
- name: "symlink - borders directory"
  file:
    src: "{{ role_path }}/files/borders"
    dest: "{{ H_XDG_CONFIG_HOME }}/borders"
    state: link
    force: true
