#!/usr/bin/env zsh
# -- BUILTIN -- #
alias cl="clear"
alias mf="touch"
alias md="mkdir"
alias gr="grep"
alias sr="source"
alias ns="netstat"
alias xa="xargs"
# -- MODULES -- #
alias nv="nvim"
alias br="brew"
alias py="python"
alias pd="podman"
alias pd-c="podman compose"
alias dk="docker"
alias dk-c="docker-compose"
alias lg="lazygit"
alias pn="pnpm"
alias ff="fastfetch"
alias ct="bat"
alias xc="pbcopy"
alias xp="pbpaste"
alias pg="nvimpager"
alias an="ansible"
alias an-pl="ansible-playbook"
alias tf="terraform"
alias pw="pwsh"
alias ls="eza --color=always --long --no-filesize --icons=always --no-time --no-user --no-permissions"
# -- DROP IN REPLACEMENTS -- #
alias python3="python"
alias pip3="pip"
alias ssh="ssh -A"
alias docker="podman"
