# -- STYLE -- #
[character]
success_symbol = " [╰─](#cba6f7)"
error_symbol = " [╰─](#cba6f7)"

# -- SYSTEM INFO -- #
[username]
format = " [╭─$user]($style)@"
style_user = "#cba6f7" # mauve
style_root = "#cba6f7" # mauve
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "#cba6f7" # mauve
trim_at = "-"
ssh_only = false
disabled = false

[directory]
style = "#89b4fa" # blue
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

[cmd_duration]
disabled = true

# -- GIT -- #
[git_branch]
style = "#eba0ac" # maroon
symbol = " "
format = "on [$symbol$branch(:$remote_branch)]($style) "

[git_status]
style = "#eba0ac" # maroon
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# -- DOCKER -- #
[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "#a6e3a1" # green
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

# -- TECHNOLOGY INFO -- #
[aws]
style = "#cba6f7" # mauve
symbol = "  "

[lua]
symbol = " "
style = "#cba6f7" # mauve
format = "via [$symbol($version )]($style)"

[golang]
style = "#cba6f7" # mauve
symbol = " "

[java]
style = "#cba6f7" # mauve
symbol = " "

[python]
symbol = " "
#pyenv_version_name = true
format = 'via [${symbol}python (${version} )(\($virtualenv\) )]($style)'
style = "#cba6f7" # mauve
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${raw}"

[rust]
style = "#cba6f7" # mauve
symbol = " "

[shlvl]
style = "#cba6f7" # mauve
symbol = " "

[swift]
style = "#cba6f7" # mauve
symbol = "ﯣ "

[nodejs]
style = "#cba6f7" # mauve
format = "via [ Node.js $version](#a6e3a1) " # green
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]
