---
- name: "ensure fonts directory exists & has correct permissions"
  file:
    path: "{{ H_HOME }}/Library/Fonts"
    state: directory
    mode: 0755
    owner: "{{ H_USER }}"
    recurse: true
  no_log: true
  become: true

- name: "get all nerdfont .ttf files"
  find:
    paths: "{{ role_path }}/files"
    recurse: true
    patterns: "*.ttf"
  register: fonts
  no_log: true

- name: "install nerdfont .ttf files"
  copy:
    src: "{{ item.path }}"
    dest: "{{ H_HOME }}/Library/Fonts"
    force: true
  loop: "{{ fonts.files }}"
  no_log: true
